### PR TITLE
Upgrade and related

### PR DESCRIPTION
**Pull request by ideas-into-software**
### Upgrades

 1. `graphql-java` – 
 
 - upgraded from version 11.0 to 19.3 (https://central.sonatype.com/artifact/com.graphql-java/graphql-java/19.3/overview); 
        
 - because, due to non-extensibility restrictions introduced by API changes in `graphql-java` bundle (private constructors, methods written to concrete types instead of interfaces, etc.), it was not possible to refactor existing Gecko GraphQL code, I introduced most minimal required changes to `graphql-java` 19.3 (https://github.com/graphql-java/graphql-java/tree/v19.3) by making constructors protected in four relevant classes where they were made private (`graphql.execution.ValuesResolver`, `graphql.schema.GraphQLFieldDefinition`, `graphql.schema.GraphQLInputObjectField`, `graphql.schema.GraphQLInputObjectType`) and assembling such bundle under version 19.3.1, which is what you will find in the Gecko GraphQL’s local repository;
 
 - this upgrade also necessitated introducing `graphql-java-extended-scalars` (https://central.sonatype.com/artifact/com.graphql-java/graphql-java-extended-scalars/19.1/overview) bundle, as it was factored out of the `graphql-java` bundle and those classes are used by Gecko GraphQL; 

     
 2. `graphql-java-servlet` – 

  - upgraded from version 7.2.0 to 15.0 (https://central.sonatype.com/artifact/com.graphql-java-kickstart/graphql-java-servlet/15.0.0/overview), which is first available version which uses Jakarta Servlet; 
  
  - this upgrade also required introducing additional bundle, `graphql-java-kickstart` (https://central.sonatype.com/artifact/com.graphql-java-kickstart/graphql-java-kickstart/15.0.0/overview), as that’s how `graphql-java-servlet` bundle was restructured;

 3. `java-dataloader` – upgraded from version 2.2.0 to 3.2.0 (https://central.sonatype.com/artifact/com.graphql-java/java-dataloader/3.2.0/overview)
 
 4. Java – upgraded to version 17 – this was necessitated by requirements of `graphql-java-servlet`, i.e. it requires Java 17;
 
 5. Apache Aries SPI Fly – upgraded to latest available version (https://central.sonatype.com/artifact/org.apache.aries.spifly/org.apache.aries.spifly.dynamic.bundle/1.3.6/overview);
 
 6. OW2 ASM – upgraded to latest available version (https://central.sonatype.com/artifact/org.ow2.asm/asm/9.4); 
 
 7. Apache Felix bundles – upgraded to latest available versions, including Apache Felix HTTP Jetty and Bridge; 
 
 8. introduced Eclipse Jetty client and transitive dependencies – because Apache Felix bundle does not include Eclipse Jetty client anymore
 
 9. upgraded Gradle

### Refactorings

 - `org.gecko.whiteboard.graphql.servlet.OsgiGraphqlWhiteboard` – synced with latest API  (latest version of `graphql.kickstart.servlet.OsgiGraphQLHttpServlet`, etc.)
 
 - `org.gecko.whiteboard.graphql.servlet.OsgiGraphqlSchemaBuilder` – introduced as per new API
 
 - `org.gecko.whiteboard.graphql.emf.execution.EMFAsyncExecutionStrategy` – synced with latest API (latest version of `graphql.execution.ExecutionStrategy`, etc.)
 
 - `org.gecko.whiteboard.graphql.emf.executation.EMFValuesResolver` – synced with latest API (latest version of `graphql.execution.ValuesResolver`, etc.)
 
 - `org.gecko.whiteboard.graphql.emf.schema.GraphQLEMFFieldDefinition` – synced with latest API
 
 - `org.gecko.whiteboard.graphql.emf.schema.GraphQLEMFInputObjectField` – synced with latest API
 
 - `org.gecko.whiteboard.graphql.emf.schema.GraphQLEMFInputObjectType` – synced with latest API
 
 - `org.gecko.whiteboard.graphql.schema.GeckoGraphQLDateScalar` – previously `GeckoScalars`
 
 - `org.gecko.whiteboard.graphql.GraphqlSchemaTypeBuilder` – synced with latest API
 
 - `org.gecko.whiteboard.graphql.GeckoGraphQLUtil` – added to handle retrieving type name with new API
 
 - `org.gecko.whiteboard.graphql.emf.EMFSchemaTypeBuilder` – synced with latest API
 
 - `org.gecko.whiteboard.graphql.service.DefaultGraphqlTypeBuilder` – synced with latest API
 
 - `org.gecko.whiteboard.graphql.service.ServiceSchemaBuilder` – synced with latest API
 
 - `org.gecko.whiteboard.graphql.instrumentation.TracingInstrumentationProvider` – synced with latest API
 
 - `org.gecko.whiteboard.graphql.emf.executation.AbsoluteGraphQLError` – synced with latest API
 
 - renamed `org.gecko.whiteboard.graphql.emf.executation` to `org.gecko.whiteboard.graphql.emf.execution`
 
 - renamed `org.gecko.whiteboard.graphql.emf.execution.EMFExecutationStrategyProvider` to `org.gecko.whiteboard.graphql.emf.execution.EMFExecutionStrategyProvider`
 
 - extracted Apache Felix dependencies to dedicated repo / "workspace extension"
 
 - removed unused dependencies (`/cnf/ext/project.maven`, `/cnf/ext/dim_nexus.maven`, `/cnf/ext/central.maven`)
 
 - removed legacy plugin build from /org.gecko.whiteboard.graphql.emf.test.model/ and included relevant directives in /org.gecko.whiteboard.graphql.emf.test.model/bnd.bnd
 
 - updated README

### Issues

This project must be put on hold due to two reasons: 

1. Latest versions of both Apache Felix HTTP Jetty (`org.apache.felix.http.jetty`) Apache Felix HTTP Bridge (`org.apache.felix.http.bridge`) support Jakarta Servlet 5.x but exclude version 6.x or above, while GraphQL Java Servlet (`graphql-java-servlet`) supports Jakarta Servlet starting at version 6.x. 

- I looked for alternatives, e.g. Glassfish, which does support Jakarta Servlet 6.x, but AFAIK `org.apache.felix.http.bridge` is needed in such setup and latest version of that bundle supports Jakarta Servlet 5.x excluding version 6.x or above.

- Side effect of this is obviously there is no servlet container in which `graphql-java-servlet` can be run, until either `org.apache.felix.http.jetty` or at least `org.apache.felix.http.bridge` support same Jakarta Servlet version as `graphql-java-servlet`.

- If you recall, we discussed Jakarta Servlet version and you mentioned version 6.x is suitable, alas, as it turned out, it is not yet supported by Apache Felix bundles we use.

- I filed an issue with both GraphQL Java Servlet and Apache Felix HTTP Jetty / Bridge projects: https://github.com/graphql-java-kickstart/graphql-java-servlet/discussions/508, https://www.mail-archive.com/users%40felix.apache.org/msg18693.html
    

2. Usage of `graphql.execution.ValuesResolver` static methods – 

 - currently, custom `AsyncExecutionStrategy` (`org.gecko.whiteboard.graphql.emf.execution.EMFAsyncExecutionStrategy`) delegates to custom `ValuesResolver` (`org.gecko.whiteboard.graphql.emf.execution.EMFValuesResolver`) - i.e. in overloaded `graphql.execution.ExecutionStrategy#createExecutionStepInfo`
 
 - unfortunately, one of the many changes in GraphQL Java was making `graphql.execution.ValuesResolver` methods static, so allowing to preserve hierarchy by making its constructor protected unfortunately is not enough, as there are over 20 different places throughout codebase where those static methods are called (`graphql.analysis.NodeVisitorWithTypeTracking`, `graphql.analysis.QueryTraverser`, `graphql.execution.ConditionalNodes`, `graphql.execution.Execution`, `graphql.execution.ExecutionStepInfoFactory`, `graphql.execution.directives.DirectivesResolver`, `graphql.execution.nextgen.ExecutionHelper`, `graphql.execution.nextgen.ValueFetcher`, `graphql.introspection.Introspection`, `graphql.introspection.IntrospectionWithDirectivesSupport`, `graphql.normalized.ExecutableNormalizedOperationFactory`, `graphql.schema.idl.FetchSchemaDirectiveWiring`, `graphql.schema.idl.SchemaPrinter`, `graphql.schema.validation.AppliedDirectiveArgumentsAreValid`, `graphql.schema.validation.DefaultValuesAreValid`, `graphql.schema.validation.TypesImplementInterfaces`, `graphql.schema.GraphQLTypeVisitorStub`, `graphql.validation.rules.VariableTypesMatch`)
 
 - This is something I discovered after most of these changes were made, as I first focused on compilation errors, so I can proceed with resolve, then tests, and after I discovered problem with Jakarta Servlet version incompatibility between GraphQL Java Servlet and Apache Felix HTTP Jetty / Bridge, I checked usage of `ValueResolver` besides how it was used in the project so far;
    
 - I filed an issue with GraphQL Java project:  https://github.com/graphql-java/graphql-java/issues/3109

### Questions

 1. Are there any other solutions, besides those mentioned in issues section above and summarized and filed as tickets with relevant projects, that you have in mind?

 2. To which versions should 'Bundle-Versions' be bumped ? Quite a lot has changed underneath, but in terms of Gecko GraphQL API changes there aren't any, at least I tried to keep it that way.

 3. Please see comments in `org.gecko.whiteboard.graphql.emf.executation.EMFValuesResolver` methods `#literalToNormalizedValueForInputObject` and `#handleInputObjectLegacy` and let me know your thoughts.

### CODE REVIEW

**Comment by juergen-albert** [comment]
I started answering to the issue you have raised in the GraphQL Project and revisited the Code in preparation. I've gotten a few ideas and I believe that I took a wrong turn during my original implementation. 

The reason I replaced their ValueResolver and subsequently extended their field definitions was the following (with some context):

In GraphQL there is no real difference between a Query and a Mutation, besides convention. Any incomming Data will go through a Value resolver end up in a `DataFetcher` . The `ServiceSchemaBuilder#DataFetcherImplementation` is the point where a request on a OSGi Service is processed. The java GraphQL can resolve any native type. Complex Objects will always become a Map in the default implementation. 

This will naturally fail when invoke is called with a Map instead of the actual Type required. 

https://github.com/geckoprojects-org/org.gecko.graphql/blob/b6e3a136477f91e04636d457401e699cd722339a/org.gecko.whiteboard.graphql/src/org/gecko/whiteboard/graphql/service/ServiceSchemaBuilder.java#L294 

I wanted to directly retrieve the actual Object at that point. Looking at it now, I'm not sure why I went down this rabbit hole, as the whole value resolver mostly diverts at the point, when I start to convert their `Map` into an `EObject`. 
https://github.com/geckoprojects-org/org.gecko.graphql/blob/b6e3a136477f91e04636d457401e699cd722339a/org.gecko.whiteboard.graphql.emf/src/org/gecko/whiteboard/graphql/emf/execution/EMFValuesResolver.java#L354

Long story short: when creating the Schema, the `ServiceSchemaBuilder` asks the `GraphqlSchemaTypeBuilder`s it has, if they can handle it and create the schema accordingly. We should have something similar for the other way around. The EMF Implementation should provider our own Version of a ValueResolver that takes a Map and transforms it to whatever Object we want (the EMF Implementation creates an EObject). 

https://github.com/geckoprojects-org/org.gecko.graphql/blob/b6e3a136477f91e04636d457401e699cd722339a/org.gecko.whiteboard.graphql/src/org/gecko/whiteboard/graphql/service/ServiceSchemaBuilder.java#L289 
Here we check if the Argument is of the same type as the expected Methodparameter. If it is of type Map, we aske our Version(s) of the ValueResolver if they can handle it and let it handle the conversion. 

A problem might become that we need the EClass we want to convert into at that point. For this you can use toe EMFModelInfo Service to get the EClass for the Parameters Java Class.

**Comment by juergen-albert** [comment]
As discussed the last time, a clarification to my comments above:

> The EMF Implementation should provider our own Version of a ValueResolver that takes a Map and transforms it to whatever Object we want (the EMF Implementation creates an EObject).

What I called a ValueResolve has nothing todo with the `ValueResolver` of GraphQL. I did not come up with a good name on the spot. For the sake of clarity, we should name it e.g. ValueConverter. The EMF Bundle could provide one Implementation of that interface.

As pseudo Code this could look as follows:

```
interface ValueConverter {
  boolean canHandle(GraphQLInputType type);

  Object convert(GraphQLInputType type, Map<String, Object> toConvert);
}
```

The DataFetcherImplementation could then be modified as follows:

```
			Object[] parameters = new Object[method.getParameterCount()];
			for (int i = 0; i < method.getParameters().length; i++) {
				Parameter parameter = method.getParameters()[i];
				if(parameter.getType().equals(DataFetchingEnvironment.class)) {
					parameters[i] = environment;
				} else {
                                        Object parameterValue = environment.getArguments().get(getParameterName(parameter));
                                        if(parameters.getType().isInstanceOf(parameterValue)){
					    parameters[i] = parameterValue;
                                        } else {
                                            // Check if there is a converter that can handle the parameter and then we convert it
                                        }
				}
			}
```

**Comment by juergen-albert** [comment]
A small thing I just realized. This projects has no Jenkinsfile yet. Would be great to have one.

**Comment by ideas-into-software** [comment]
https://github.com/geckoprojects-org/org.gecko.graphql/pull/2 is a continuation

**Pull request closed without merging**
